export const mockWords = [
  {
    id: '1',
    word: 'transport',
    phonetic: '/trænsˈpɔːrt/',
    partOfSpeech: 'v. / n.',
    meaning: '运输；交通工具',
    rootAnalysis: 'trans-（穿过）+ port（携带）→ "转移-携带" → 运输',
    memoryTip: '想象把东西trans(转移)到另一个port(港口)',
    relatedWords: ['export', 'import', 'portable', 'report', 'support'],
    example: {
      sentence: 'The goods were transported by rail to the warehouse.',
      translation: '货物通过铁路运输到仓库。',
      source: '2021 高考英语阅读',
    },
    collocations: [
      { phrase: 'public transport', meaning: '公共交通' },
      { phrase: 'transport system', meaning: '交通系统' },
      { phrase: 'air transport', meaning: '航空运输' },
    ],
  },
  {
    id: '2',
    word: 'accomplish',
    phonetic: '/əˈkɑːmplɪʃ/',
    partOfSpeech: 'v.',
    meaning: '完成；实现；达到',
    rootAnalysis: 'ac-（加强）+ com-（一起）+ plish（填满）→ 彻底完成',
    memoryTip: '联想：a company(一个公司)要accomplish(完成)目标',
    relatedWords: ['accomplishment', 'accomplished', 'complete', 'achieve'],
    example: {
      sentence: 'She accomplished her goal of running a marathon.',
      translation: '她实现了跑马拉松的目标。',
      source: '2020 四级阅读',
    },
    collocations: [
      { phrase: 'accomplish a task', meaning: '完成任务' },
      { phrase: 'accomplish a goal', meaning: '实现目标' },
      { phrase: 'accomplish nothing', meaning: '一事无成' },
    ],
  },
  {
    id: '3',
    word: 'abundant',
    phonetic: '/əˈbʌndənt/',
    partOfSpeech: 'adj.',
    meaning: '充裕的；丰富的；大量的',
    rootAnalysis: 'ab-（离开）+ und（波浪）+ ant → 像波浪般涌来 → 大量的',
    memoryTip: '想象 a bun dance(一个面包在跳舞)，面包很abundant(丰富的)',
    relatedWords: ['abundance', 'abundantly', 'redundant', 'inundate'],
    example: {
      sentence: 'The region has abundant natural resources.',
      translation: '该地区拥有丰富的自然资源。',
      source: '2019 六级阅读',
    },
    collocations: [
      { phrase: 'abundant in', meaning: '在...方面很丰富' },
      { phrase: 'abundant resources', meaning: '丰富的资源' },
      { phrase: 'abundant evidence', meaning: '充分的证据' },
    ],
  },
  {
    id: '4',
    word: 'beneath',
    phonetic: '/bɪˈniːθ/',
    partOfSpeech: 'prep. / adv.',
    meaning: '在...之下；在...的下方',
    rootAnalysis: 'be-（在）+ neath（下方，来自nether）→ 在下方',
    memoryTip: 'be + neat + h → 在neat(整洁的)表面below(下面)隐藏着什么',
    relatedWords: ['underneath', 'below', 'under', 'nether'],
    example: {
      sentence: 'The boat sank beneath the waves.',
      translation: '小船沉入了波浪之下。',
      source: '经典文学 - 老人与海',
    },
    collocations: [
      { phrase: 'beneath the surface', meaning: '在表面之下' },
      { phrase: 'far beneath', meaning: '远在下方' },
      { phrase: 'beneath contempt', meaning: '不屑一顾' },
    ],
  },
  {
    id: '5',
    word: 'compassion',
    phonetic: '/kəmˈpæʃn/',
    partOfSpeech: 'n.',
    meaning: '同情心；怜悯',
    rootAnalysis: 'com-（一起）+ pass（忍受/感受）+ ion → 一起感受痛苦 → 同情',
    memoryTip: '联想：come + passion(激情) → 带着激情来同情别人',
    relatedWords: ['compassionate', 'passion', 'passive', 'patient'],
    example: {
      sentence: 'He showed great compassion for the victims.',
      translation: '他对受害者表现出极大的同情。',
      source: 'BBC News 2022',
    },
    collocations: [
      { phrase: 'show compassion', meaning: '表示同情' },
      { phrase: 'with compassion', meaning: '带着同情心' },
      { phrase: 'compassion fatigue', meaning: '同情疲劳' },
    ],
  },
  {
    id: '6',
    word: 'deliberate',
    phonetic: '/dɪˈlɪbərət/',
    partOfSpeech: 'adj. / v.',
    meaning: 'adj. 故意的；深思熟虑的 v. 仔细考虑',
    rootAnalysis: 'de-（完全）+ liber（称量/天秤）+ ate → 仔细称量 → 深思熟虑的',
    memoryTip: '在de-liberate(图书馆)里要deliberate(仔细考虑)',
    relatedWords: ['deliberately', 'deliberation', 'liberty', 'liberal'],
    example: {
      sentence: 'It was a deliberate attempt to mislead the public.',
      translation: '这是一次故意误导公众的企图。',
      source: 'The Guardian 2021',
    },
    collocations: [
      { phrase: 'deliberate act', meaning: '蓄意行为' },
      { phrase: 'deliberate decision', meaning: '深思熟虑的决定' },
      { phrase: 'deliberate over', meaning: '仔细考虑' },
    ],
  },
  {
    id: '7',
    word: 'elaborate',
    phonetic: '/ɪˈlæbərət/',
    partOfSpeech: 'adj. / v.',
    meaning: 'adj. 精心制作的；详尽的 v. 详细阐述',
    rootAnalysis: 'e-（出来）+ labor（劳动）+ ate → 用劳动做出来 → 精心制作的',
    memoryTip: '想象一个e-labor(电子工人)精心elaborate(制作)产品',
    relatedWords: ['elaboration', 'labor', 'collaborate', 'laboratory'],
    example: {
      sentence: 'Could you elaborate on your proposal?',
      translation: '你能详细阐述一下你的提案吗？',
      source: '2020 考研英语',
    },
    collocations: [
      { phrase: 'elaborate plan', meaning: '精心策划' },
      { phrase: 'elaborate on', meaning: '详细阐述' },
      { phrase: 'elaborate design', meaning: '精巧的设计' },
    ],
  },
  {
    id: '8',
    word: 'facilitate',
    phonetic: '/fəˈsɪlɪteɪt/',
    partOfSpeech: 'v.',
    meaning: '促进；使...变容易',
    rootAnalysis: 'facil（容易的, 来自facile）+ itate → 使变得容易 → 促进',
    memoryTip: 'face(脸)+il+itate → 给个笑脸让事情变容易facilitate',
    relatedWords: ['facility', 'facile', 'facilitate', 'factor'],
    example: {
      sentence: 'Technology can facilitate communication between teams.',
      translation: '技术可以促进团队之间的沟通。',
      source: 'Harvard Business Review',
    },
    collocations: [
      { phrase: 'facilitate learning', meaning: '促进学习' },
      { phrase: 'facilitate communication', meaning: '促进沟通' },
      { phrase: 'facilitate growth', meaning: '促进增长' },
    ],
  },
];
